[step1] buildMethod를 Widget으로 분리
next-step/fb-cart-sample pull request #20
Opened 2022-11-03 15:54 UTC by JihyeonNam-0327

- buildMethod로 구현된 코드들을 Widget으로 구현
- Stateless Widget으로 구현
- 음식점 이름, 메뉴 이름은 데이터를 생성자로 전달
- Intl 라이브러리 활용해서 가격에 formatter 적용

2022-11-04 13:56 UTC, tidyline requested changes
첫 번째 과제 하시느라 고생 많으셨어요 🎉 

과제 요건에 맞추셔서 과제를 잘 수행해주신 것으로 보입니다~
과제이긴 하지만 실제로 서비스로 구현한다면 이렇게 하면 좋겠다 싶었던 부분들을 남겨두었습니다!
커멘트로 남겨드린 부분들을 한 번 수정해보시고 다음 과제로 넘어가면 좋을 것 같아요 😄

2022-11-04 13:56 UTC, tidyline commented on lib/cart_screen.dart
> +                  f.format(21000) + ' 배달 주문하기',
dart 언어에서 string concatenate 하는 방법이 여러개 있는데요~
https://dart.dev/guides/language/language-tour#strings
```
'${f.format(21000)} 배달 주문하기'
```

요렇게도 사용할 수 있습니다~

2022-11-04 13:56 UTC, tidyline commented on lib/cart_screen.dart
> +class _StoreName extends StatelessWidget {
cart_screen 내에 있는 위젯들을 각각의 파일로 분리해서 한 번 수정해보시겠어요? 
cart_screen 내에 많은 위젯들이 있어서 코드 가독성면에서 분리되는 것이 좋을 것 같습니다~

2022-11-04 13:56 UTC, tidyline commented on lib/cart_screen.dart
> +                  Text(f.format(18000)),
menuName 뿐만이 아니라 menuPrice 역시 주입받으면 좋을 것 같은 값으로 보여요~
이 화면을 실제로 api와 연동해서 구현해야 한다고 생각하면,
이런 값들은 api 에서 받아서 보여주는 값이 될 것 같아요~
그래서 각 위젯별로 이런 값들이 있으면 한 번 분리해보는 것을 추천드립니다~

2022-11-04 13:56 UTC, tidyline commented on lib/cart_screen.dart
> +  final menuName;
요렇게 작성해주신 부분도 좋지만,
다트에서 `_` underscore 를 사용하면 변수가 private 이 됩니다~
둘 중에서 서로 어떤 차이가 있는지, 어떤 이점들이 있는지 등을 한 번 생각해보시고 수정해보시면 좋을 것 같아요!!

> Unlike Java, Dart doesn’t have the keywords public, protected, and private. If an identifier starts with an underscore (_), it’s private to its library. For details, see [Libraries and visibility](https://dart.dev/guides/language/language-tour#libraries-and-visibility).

2022-11-04 13:56 UTC, tidyline commented on lib/cart_screen.dart
> +var f = NumberFormat('###,###,###,###원'); // 천단위 구분기호 추가
이 부분도 실제 실서비스를 구현한다고 생각하면 여러곳에서 사용할 수 있게 파일로 분리해보는 것이 좋을 것 같아요~

2022-11-04 13:56 UTC, tidyline commented on lib/cart_screen.dart
> +              menuName: "후라이드 반 양념 반",
요기 named parameter 로 잘 구현을 해주셨네요~ 👍

2022-11-07 11:51 UTC, JihyeonNam-0327 commented on lib/cart_screen.dart
> +                  f.format(21000) + ' 배달 주문하기',
오 자바스크립트랑 비슷하네요 : ) 그렇게 수정해볼게요 !

2022-11-07 11:52 UTC, JihyeonNam-0327 commented on lib/cart_screen.dart
> +class _StoreName extends StatelessWidget {
👍 파일로 분리 적용해볼게요 : )

2022-11-07 11:54 UTC, JihyeonNam-0327 commented on lib/cart_screen.dart
> +  final menuName;
파일로 분리하게 된다면 public 으로 선언해야겠지요 : ) 파일 분리하면서 함께 변경하도록 해볼게요 ㅎㅎ

2022-11-07 12:13 UTC, JihyeonNam-0327 commented on lib/cart_screen.dart
> +                  Text(f.format(18000)),
cart screen 에서 api 를 호출한다고 생각하고, 넘겨줄 수 있는 값들은 분리적용해 볼게요 : )

2022-11-07 12:21 UTC, JihyeonNam-0327 commented on lib/cart_screen.dart
> +var f = NumberFormat('###,###,###,###원'); // 천단위 구분기호 추가
분리하고 선언한 변수를 어떻게 Import 해줘야 하나 고민했는데, 별 다른 조치 없이도 분리한 파일의 variable f 를 인식하네요.. 😮

2022-11-07 12:22 UTC, JihyeonNam-0327 commented
말씀해주신 사항 반영했습니다 : ) 꼼꼼히 봐주셔서 감사해요 👍

2022-11-07 13:15 UTC, tidyline approved these changes
리뷰 반영해주신 것 잘 봤습니다~ 고생많으셨어요 🎉 

추가로 코멘트 남겨드린 것은 다음 pr 에 함께 수정해보시면 좋을 것 같습니다.

나눠 주신 widget 들을 보면.. 원래 cart_screen 에서만 사용되었는데,
파일로 분리되면서 다른 곳에서도 접근 가능한 상태가 되었는데요~
만약 cart_screen에서만 사용되게 하고 싶으면 part-part of 를 사용할 수 있을 것 같습니다.
다음 pr 에서 위젯 하나만 요렇게 바꿔보는 것을 추천드립니다 :) 
https://github.com/next-step/flutter-cart-sample/pull/1#pullrequestreview-1086807145

다음 단계 진행해주시면 될 것 같습니다~

2022-11-07 13:15 UTC, tidyline commented on lib/cart_screen_widget/Billing.dart
> +  final int sumMenuPrice;
deliveryPrice, sumMenuPrice 등 각 위젯에서 사용되는 멤버변수는 외부에서 접근할 필요가 없기 때문에 private으로 한 번 바꿔보시겠어요?

2022-11-07 13:15 UTC, tidyline commented on lib/util/numberFormat.dart
> +final f = NumberFormat('###,###,###,###원'); // 천단위 구분기호 추가
외부에서 사용할 때  f 라는 값이 어떤 것인지 바로 알기 어려우니 
변수명을 좀 더 가독성 있게 바꿔보는 것을 추천드립니다~

2022-11-07 13:16 UTC, merged

2022-11-07 13:28 UTC, tidyline commented on lib/cart_screen.dart
> +var f = NumberFormat('###,###,###,###원'); // 천단위 구분기호 추가
저도 프론트엔드 개발을 하다보니.. 
보통 import 시 `import {f} from 'utils'` 이런식으로 사용하다가
dart 에서는 이런 개념이 없는 것 같아서 조금 불편했었어요 😓 

```
import 'package:intl/intl.dart';
```

intl 의 경우에도 `import {NumberFormat} from 'package:intl/intl.dart';`
이렇게 하면 좋을 것 같던데 그렇지 않더라구요 😄 

그래서 class 로 묶어주는 방법도 생각해 볼 수 있을 것 같습니다~

```
class NumberUtils {
   String formatCurrency () {...}
   String format () {..}
}
```

물론

```
String formatCurrency () {
...
}
```
바로 함수로 선언해서 써도 되지만요~

예전에 강사님께서 알려주신 링크인데,
https://github.com/dart-lang/intl/blob/7e3a1bbdeff241323f56295d8991c004bef815e6/lib/intl.dart#L68
dart 내부에서도 class, 전역 함수로 사용하는 부분이 혼재되어있긴 했어요~

2022-11-07 13:32 UTC, JihyeonNam-0327 commented on lib/cart_screen.dart
> +var f = NumberFormat('###,###,###,###원'); // 천단위 구분기호 추가
오 class 로 묶어주는 것도 매우 좋네요!!!